services:
  sip-server:
    image: sip-server-v2:${IMAGE_TAG:-latest}
    container_name: sip-server
    restart: unless-stopped

    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

    network_mode: host

    command: ["/bin/bash", "./run.sh"]

    volumes:
      - /opt/home/matthew/Desktop/docker/sip_server/app/output:/app/output
      - /opt/home/matthew/Desktop/docker/sip_server/app/recording:/app/recording
      - /opt/home/matthew/Desktop/docker/sip_server/app/voices:/app/voices:ro
      # - /opt/home/matthew/Desktop/docker/sip_server/app/output/transcode/greeting.wav:/app/output/transcode/greeting.wav:ro

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
